### ISSUE TITLE
expanded display at initialization

### ISSUE THREAD

**Issue by damda58** [rwbr/flutter_neat_and_clean_calendar#12]
Hello,

Is it possible to have the display extended on load like this?

![image](https://user-images.githubusercontent.com/6893451/117054016-f0c28680-ad19-11eb-98cd-36dc6a0f272e.png)

No matter the value of isExpandable and isExpanded I only have the display on one line

![image](https://user-images.githubusercontent.com/6893451/117054428-6169a300-ad1a-11eb-9167-321c3eb64ca7.png)

Thanks for this dependencies

**Comment by rwbr** [comment]
Ok, I'll have a look at it.

**Comment by rwbr** [comment]
This issue is fixed in v0.2.2+10 of the package.

**Comment by damda58** [comment]
thanks, it's work now !
