### ISSUE TITLE
Scroll in calendar

### ISSUE THREAD

**Issue by blendosantos** [rwbr/flutter_neat_and_clean_calendar#16]
When the screen has a scroll and we need to drag clicking on any area of the calendar the scroll does not work.

Example: The screen using SingleChildScrollView with an image and just below the calendar, when I click on the date or the description of the week I can't drag the screen, only when I click on the empty areas or on the descriptive year/month

![Here's print.](https://user-images.githubusercontent.com/8852312/135463003-f49d6264-60fe-40c2-8127-2ac84084eb35.png)

**Comment by rwbr** [comment]
Hi!
Could you please publish a code fragment to illustrate this issue? I'll have a look into it.

**Comment by rwbr** [comment]
Sorry, if you can't show some sample code, so that I'm able to see that problem in action, I will be unable to help.
