### ISSUE TITLE
How to show date today?

### ISSUE THREAD

**Issue by gus-ka** [rwbr/flutter_neat_and_clean_calendar#18]
i have a custom button to show date today.
how to do that?

**Comment by rwbr** [comment]
Take a look into the source code. It's all documented:

```
/// [initialDate] is of type [DateTime]. It can contain an optional start date. This is the day, that gets initially selected
///     by the calendar. The default is to not set this parameter. Then the calendar uses [DateTime.now()]

```

The `Calendar `class has a property called `initialDate`. If you like to create a custom button, that forces the calendar view to jump to today's date, this button just has to force the widget to render. I think there's not much more necessary as a stateful widget with your custom button and the calendar. Then when the user presses the button just re-render the whole widget using the `setState()` method.

**Comment by gus-ka** [comment]
Got it. thankyou.
