### ISSUE TITLE
Color change?

### ISSUE THREAD

**Issue by MarcelHH** [rwbr/flutter_neat_and_clean_calendar#2]
Hi how i can change the colors of 
Days, Header Arrows and Date? 
How i can add Border to days and remove the event list? 
How i can change days with event have not a Dot have a background color

**Comment by rwbr** [comment]
You can influence the styling of the current day with the parameter `dayOfWeekStyle `. 
If you wish to use a custom style (including boaders) the days, set the `dayBuilder` parameter with your own custom widget. 
At the moment, there is no way to set the style of arrows and date. 
If you set `eventColor` to `Colors.transparent`, the dots should disappear.
