### ISSUE TITLE
Minimum and Maximum date Feature

### ISSUE THREAD

**Issue by Ankit0080** [rwbr/flutter_neat_and_clean_calendar#20]
Currently  there is no  minmum and maximum date feature available in calendar. And the left and right arrow click function not available

**Comment by rwbr** [comment]
Sorry for the late reaction. Could you please explain, what minimum and maximum date feature means? What means left and right arrow click function not available?

**Comment by rwbr** [comment]
Closing this issue due to lack of contribution.
