### ISSUE TITLE
Multi-day events

### ISSUE THREAD

**Issue by cremfert** [rwbr/flutter_neat_and_clean_calendar#22]
First of all, thanks a lot for developing such a great widget - it really helps me!

I just have one question: is it possible to have events that span over multiple days? For example, if I specify startdate as today and enddate in two days, the calendar only shows the event only on today.

What would be the recommend approach to deal with this?

Thanks a lot!

**Comment by rwbr** [comment]
This package is a calendar UI library. It provides a UI for a calendar. The API of the library expects you a the user of the package to give it a Map of calendar events as a parameter:

```dart
Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Calendar(
          startOnMonday: true,
          weekDays: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
          events: _events, // Here you pass the map of calendar events to the library
          isExpandable: true,
          eventDoneColor: Colors.green,
```

You pass the `events` to be shown on the calendar UI. So it's your apps task to fill the map according to your needs. The library just uses this map to display the events. But it has no logic for multi-day events. 

I don't know, if this will come in a later release.

Would you please make a suggestion, how such events that span over multiple days, would look like in the UI? How would the lock different from separate events all with the same title and color?

**Comment by rwbr** [comment]
From v0.3.0+13 on the library handles multi-day events. To make use of it you need to use the property `final List<NeatCleanCalendarEvent>? eventsList;`

**Comment by cremfert** [comment]
This is superior, thanks a lot!
