### ISSUE TITLE
Add event?

### ISSUE THREAD

**Issue by MarcelHH** [rwbr/flutter_neat_and_clean_calendar#3]
Hey wie kann man ein Event einfügen? also nicht per hand sondern generieren zB aus eine liste von datums!

**Comment by rwbr** [comment]
Die Kalender-Events werden nicht im Widget gespeichert oder verarbeitet. Die Verwaltung der Events erfolgt in einer Business-Logic-Klasse (nicht Teil des Projekts). Diese liefert die Liste er Widgets als `List<NeatCleanCalendarEvent>` aus, beispielsweise über einen Stream. 
Das Widget sitzt im Widget-Tree beispielsweise unter einem StreamController und wird dadurch bei Änderungen im Stream jedesmal neu gerendert. So sind UI-Layer und Business-Logic sauber getrennt. 
Deine App benötigt also eine Business-Logic-Komponente, die die Events ausliefert. Wie die aussieht ist aber nicht Teil meines Projekts.

**Comment by MarcelHH** [comment]
ich weiß jetzt nicht was eine Buisness Logik ist aber ich habe es mit 

 _events.addAll({
      DateTime(jahr, monat, tag): [
        NeatCleanCalendarEvent(
          '',
          startTime: DateTime(jahr, monat, tag),
          endTime: DateTime(jahr, monat, tag),
        ),
      ],
    });

geschaft events eizufügen, momentan ist nur das problem man mus den kalender einmal nach lionks oder recht klicken um das ergebniss zu sehen

**Comment by rwbr** [comment]
Ich kenne jetzt Deinen Code nicht, aber Du solltest das Kalender-Widget in ein Stateful-Widget einbetten und dann dessen `setState()`-Methode aufrufen, wenn Du die Events hinzugefügt hast. Dann sollte das Kalender-Widget neu gerendert werden und den heutigen Tag bzw. Monat anzeigen, inklusive der neuen Events.

**Comment by MarcelHH** [comment]
Es ist ja in ein Statefull-Widget meine Daten kommen aus einer Datenbank,

habe nur 2 probleme erst nachdem ich den kalender bewegt habe sehe ich ein even aber nur 1, mache ich irgendein fehler und entferne ihn wieder dann zeigt er mir plötzlich alle an echt komisch, hier ist mein code


`class WochenUberblick extends StatefulWidget {
  final Task task;
  final Function updateTaskList;

  const WochenUberblick({
    Key key,
    this.task,
    this.updateTaskList,
  }) : super(key: key);

  @override
  _WochenUberblickState createState() => _WochenUberblickState();
}

class _WochenUberblickState extends State<WochenUberblick> {
  Future<List<Task>> _taskList;

  @override
  void initState() {
    super.initState();
    _updateTaskList();
  }

  _updateTaskList() {
    setState(() {
      _taskList = DBHelper.instance.getTaskList();
    });
  }

  Map<DateTime, List<NeatCleanCalendarEvent>> _events = {};

  addtolist(int jahr, int monat, int tag) {
    _events.addAll({
      DateTime(jahr, monat, tag): [
        NeatCleanCalendarEvent(
          '',
          startTime: DateTime(jahr, monat, tag),
          endTime: DateTime(jahr, monat, tag),
        ),
      ],
    });
  }

  returner(Task task) {
    return addtolist(task.date.year, task.date.month, task.date.day);
  }

  calender() {
    return Container(
      padding: EdgeInsets.only(left: 10, right: 10, top: 15),
      margin: EdgeInsets.only(top: 0),
      decoration: BoxDecoration(
        gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [
              Color.fromRGBO(25, 29, 32, 1),
              Color.fromRGBO(34, 37, 42, 1),
            ]),
      ),
      height: 150,
      child: SafeArea(
        child: Calendar(
          startOnMonday: true,
          weekDays: [
            AppLocalizations.of(context).translate('mo'),
            AppLocalizations.of(context).translate('di'),
            AppLocalizations.of(context).translate('mi'),
            AppLocalizations.of(context).translate('do'),
            AppLocalizations.of(context).translate('fr'),
            AppLocalizations.of(context).translate('sa'),
            AppLocalizations.of(context).translate('so')
          ],
          events: _events,
          isExpandable: false,
          selectedColor: Colors.transparent,
          todayColor: Colors.blue,
          eventDoneColor: Colors.green,
          eventColor: Colors.red,
          hideTodayIcon: true,
          locale: AppLocalizations.of(context).translate('traininglocal'),
          todayButtonText: 'Heute',
          expandableDateFormat: 'EEEE, dd. MMMM yyyy',
          dayOfWeekStyle: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.bold,
            fontSize: 11,
          ),
          eventListBuilder: (BuildContext context,
              List<NeatCleanCalendarEvent> _selectesdEvents) {
            return SizedBox();
          },
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        calender(),
        EventFuture(_taskList, returner), // ist ein FutureBuilder
      ],
    );
  }
}
`

**Comment by rwbr** [comment]
Mmh, `_updateTaskList ` gibt ein `Future<List<Task>> ` zurück, was dann in der `build`-Methode an `EventFuture(_taskList, returner) ` übergeben wird. `returner ` ist hier offenbar eine Callback-Methode. 
Das ganze wird ausgelöst über den Aufruf von `_updateTaskList(); ` in der `initState`-Methode. 

Ich weiß nicht, was das genau schief geht. Aber ich vermute, dass das durch den asynchronen Code verursacht wird. Die `build`Methode wird durch `setState` getriggert, aber ich glaube nicht, dass zu dem Zeitpunkt bereits die Future "resolved" wurde. 

Du könntest den Aufruf der `getTaskList` mit `await` kennzeichnen. Dann muss sich allerdings der Typ von _taskList auch ändern. 
```
_updateTaskList() async {
    setState(() {
      _taskList = await DBHelper.instance.getTaskList();
    });
  }
```

Noch besser wäre es, wenn Du einen FutureBuilder verwendest, da das Widget dann erst rendert, wenn die Future abläuft:

```
@override
  Widget build(BuildContext context) {
    return FutureBuilder<List<Event>>(
      future: DBHelper.instance.getTaskList(),
     builder: (context, AsyncSnapshot<List<Task>> snapshot) {
       if (snapshot.hasData) {
        return Column(
          children: [
            calender(),
             EventFuture(_taskList, returner), // ist ein FutureBuilder
          ],
        );
...
       }
    }
  }
```

Aber auch dabei ändert sich der Typ von `_taskList` zu `List<Task>`.

**Comment by MarcelHH** [comment]
Ja das mit await funktioniert nicht :( ich sitzt da schon so lange dran und bekomme das nicht hin.

die daten kommen von sqlflite

```
  Future<List<Task>> getTaskList() async {
    final List<Map<String, dynamic>> taskMapList = await getTaskMapList();
    final List<Task> taskList = [];
    taskMapList.forEach((taskMap) {
      taskList.add(Task.fromMap(taskMap));
    });

    taskList.sort((taskA, taskB) => taskB.date.compareTo(taskA.date));
    return taskList;
  }
```

ka was ich noch machen soll eigentlich sollte es ja nicht so schwer sein.

**Comment by rwbr** [comment]
Ich denke, Dein Problem ist, dass initState aufgerufen wird, wenn das Widget in den WidgetTree eingehängt wird. Dein Code ruft dann Datenbank-Funktion auf, die ein Future liefert. Die Ansicht wird auf den Aufruf von setState hin gerendert, egal ob das Future bis dahin ein Ergebnis geliefert hatte. Anschließend wird es aus Deinem Code nie wieder gerendert. 
Integriere mal einen FutureBuilder (so wie ich das oben vorgeschlagen hatte), um die Datenbank-Abfrage auszuführen. Der Rest kann wahrscheinlich so bleiben. Dadurch wird das Rendern der Ansicht nach Fertigstellung der Abfrage erzwungen.

**Comment by MarcelHH** [comment]
Das geht nicht schau mal hier was da kommt

[](https://imgur.com/GvfKXZY)
[](https://imgur.com/hj3SwoL)

**Comment by rwbr** [comment]
Oh, mein Fehler! Der Typ des FutureBuilder ist falsch definiert. Es muss heißen:
`return FutureBuilder<List<Event>>(`

**Comment by MarcelHH** [comment]
Das ist doch genau so wie ich es habe schau auf den bild 1 zu 1 :)

**Comment by rwbr** [comment]
Jetzt sollte es aber passen. Ich habe die Zeile noch mal editiert.

**Comment by MarcelHH** [comment]
Ok der fehler von bild 1 ist weg der von bild 2 ist noch da!

und wenn ich die seite aufrufe kommt ganz kurz eine fehlerseite und dann die normale

```
The following assertion was thrown building FutureBuilder<List<Task>>(dirty, state: _FutureBuilderState<List<Task>>#99905):
A build function returned null.
```

und alle ist wie vorher das problem ist das gleiche :(

**Comment by rwbr** [comment]
Da felhlt wahrscheinlich der else-Zweig für `if Snapshot.hasData)`, weil sonst die Build-Funktion null liefern kann. Das ist nicht zulässig.

**Comment by MarcelHH** [comment]
Ja stimmt, der fehler ist jetzt weg.

dennoch stehe ich genau da wo ich schon vorher war, alles beim alten 😥

**Comment by MarcelHH** [comment]
Wenn ich aus

```
  returner(Task task) {
    return addtolist(task.date.year, task.date.month, task.date.day);
  }

```
das mache

```
  returner(Task task) async {
    return addtolist(task.date.year, task.date.month, task.date.day);
  }
```

Dann bekomme ich zwar ein fehler type 'Future<dynamic>' is not a subtype of type 'Widget'

und der Column Bereich ist rot aber zumindest im Kalender sehe ich dann alle events aber auch erst nachdem ich einmal nach links oder rechts gegangen bin! ka was das zu bedeuten hat aber vieleicht kannst du daraus mehr infos ziehen!?

**Comment by MarcelHH** [comment]
Update:

ich hab jetzt das gemacht

```
 @override
  Widget build(BuildContext context) {
    return FutureBuilder<List<Task>>(
        future: _taskList,
        builder: (context, AsyncSnapshot<List<Task>> snapshot) {
          if (snapshot.hasData) {
            return Column(
              children: [
                ListView.builder(
                  shrinkWrap: true,
                  itemCount: snapshot.data.length,
                  itemBuilder: (BuildContext context, int i) {
                    return returner(snapshot.data[i]);
                  },
                ),
                calender(),
              ],
            );
          } else {
            return Text('');
          }
        });
  }
}
```

Damit zeigt er mir jetzt zumindest sofort den einen event an ohne das ich nach links oder rechts muss! jetzt muss er mir nur noch alle events zeigen nicht nur den einen 😀

**Comment by rwbr** [comment]
Not a bug. Problem resulted from the users app code. Closing issue.
