### ISSUE TITLE
[Feature Request] Add scrollable PageView like for calendar 

### ISSUE THREAD

**Issue by Mayb3Nots** [rwbr/flutter_neat_and_clean_calendar#31]
It would be nice to be able to scroll with animation and can peek the next page.

**Comment by rwbr** [comment]
I think, I need some more input on this request. Wiche area do you want to scroll? The events list?

**Comment by Mayb3Nots** [comment]
Here at this part I wanna make the `Column` into a `PageView.builder` so that we can have the animation and view of the next page instead of a instant setState changing the calendar.
 https://github.com/rwbr/flutter_neat_and_clean_calendar/blob/9b5948ad07b38e5b0a27804253e4710a70d622d7/lib/flutter_neat_and_clean_calendar.dart#L410-L422

I have actually taken a look at the source code and brainstorming how to make it possible, I will say it won't be an easy task because of how this plugin is written.
