### ISSUE TITLE
If startOnMonday == false, expanded view is shifted by one day.

### ISSUE THREAD

**Issue by eugenedina** [rwbr/flutter_neat_and_clean_calendar#32]
I don't think the expanded (month view) is taking into account the startOnMonday flag. 
When viewing week... with startOnMonday = false.
![image](https://user-images.githubusercontent.com/7925832/159767986-8f388311-ea7e-4153-b4ed-9a33c764ea1b.png)

Upon expanding...

![image](https://user-images.githubusercontent.com/7925832/159768064-caa02394-dca5-4956-9025-07c24873fcd6.png)

with startOnMonday == true, both week and month view are correct. 

Happy to provide a fix if you want it.

**Comment by rwbr** [comment]
I'm able to reproduce the bug. Will find a fix for it. You're welcome to suggest a solution.
