### ISSUE TITLE
[Feature Request] Allow for providing a default day color

### ISSUE THREAD

**Issue by eugenedina** [rwbr/flutter_neat_and_clean_calendar#34]
When viewing the expanded calendar, there doesn't seem to be a way the color for days within a month, but not the selected day. I'd like to propose providing a property on  calendar that is passed down to the tile to provide this. I have made the necessary changes on my fork and can create a pull request if you'd like. 

Because of my dark theme, the calendar ends up looking like this, making it very hard to read. 
![image](https://user-images.githubusercontent.com/7925832/159935969-114589b0-e74f-4c19-9e1c-d2172d790a10.png)

This property would allow me to customize it as such. 
![image](https://user-images.githubusercontent.com/7925832/159936082-3cf94be4-0039-4591-82f2-ce1a51be656a.png)

May not be a bad idea to also introduce a var for the default gray used for previous and next months' days.

**Comment by rwbr** [comment]
I get you point. Should be easy to fix. You contribution is highly welcome. Please share your code. 

BTW: The more color option the package supports, the more it might be a good move to use something like a dedicated ThemeData object to configure these settings.

**Comment by eugenedina** [comment]
Excellent. I'll issue a pull request. I'll also make the changes for the default grey for non month days, if that's ok. Completely agree on ThemeData for a longer term solution. I've settled on this calendar for my project, so I'm invested in it now :) I'm happy to also work on this longer term solution.

**Comment by rwbr** [comment]
Closed with #35
