### ISSUE TITLE
When startonMonday is false. Sunday calendar 📆 does not show, if not expanded.

### ISSUE THREAD

**Issue by usernamekk** [rwbr/flutter_neat_and_clean_calendar#4]
![Screenshot_20210411-013320](https://user-images.githubusercontent.com/28014560/114288262-feac2100-9a65-11eb-83f4-0f9a151bbcdf.png)

The date is Sunday 11 April but doesn't show on calendar.

**Comment by rwbr** [comment]
I can confirm this bug. Now investigating.
