### ISSUE TITLE
Selecting new date calls onMonthChanged

### ISSUE THREAD

**Issue by Mmisiek** [rwbr/flutter_neat_and_clean_calendar#41]
Hi,
This is a great plugin but I think there is an issue with onMonthChanged.
In my app it is called each time I select new data, even from same month.

It would be cool if you would provide default add event dialog.
Thanks
Michal

**Comment by jjvillavicencio** [comment]
Hi, I have the same problem when I select a specific day in the calendar, the plugin calls the MonthChanged event, and the event that should be called is only onDateSelected

**Comment by rwbr** [comment]
I could change the logic in `_launchDateSelectionCallback` to only trigger that callback function when the month or the year caged indeed. 

```dart
    if (widget.onMonthChanged != null && day.month != _selectedDate.month || day.year != _selectedDate.year) {
      widget.onMonthChanged!(day);
    }
```

I guess that would solve the problem. In case the user selected a different day of the same month the callback would not be called, which should be the correct behavior.
