### ISSUE TITLE
Previous week then selected date wrong one date late

### ISSUE THREAD

**Issue by Kimsoer** [rwbr/flutter_neat_and_clean_calendar#43]
Dear team , I would like to thank for your great library, I have issue while selected after previous week one time, it will wrong one date late example i selected 02-10-2022 but it show 01-10-2022. thank you

**Comment by rwbr** [comment]
Thank you for your feedback. Could you please give me some more information? How can I reproduce the faulty behavior? 
Please describe the steps to reproduce the bug in detail.

**Comment by Kimsoer** [comment]
Thank for response my message , 
The steps  are :
1.Open as Expanded = false it will show one week
<img width="315" alt="Screen Shot 2022-10-04 at 1 23 19 PM" src="https://user-images.githubusercontent.com/44362669/193748959-87a912b6-30fe-4eba-aaa5-a8d3e447b79e.png">
2.Press arrow to previous week 
<img width="331" alt="Screen Shot 2022-10-04 at 1 24 42 PM" src="https://user-images.githubusercontent.com/44362669/193749059-7e3ec2af-7da6-4531-985e-90be5014ca1d.png">
3.Click selected on 02- sept-2022
but the data result of selected is 01-sept-2022
<img width="322" alt="Screen Shot 2022-10-04 at 1 26 46 PM" src="https://user-images.githubusercontent.com/44362669/193749341-f39d39c8-21da-4189-8436-6d28c3ea745e.png">
Please see my print log result : 
<img width="482" alt="Screen Shot 2022-10-04 at 1 26 22 PM" src="https://user-images.githubusercontent.com/44362669/193749401-a5b6f584-d287-42bd-ba93-c9d7ed4254f2.png">

**Comment by rwbr** [comment]
Great. Thank you, I guess that helps a lot. I will look into it as soon as possible.

**Comment by rwbr** [comment]
I'm still having problems reproducing the error behavior in your observations. Following your guide I get the following behavior:

## Open as Expanded = false it will show one week

![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-26 at 15 06 49](https://user-images.githubusercontent.com/144948/209556943-bd3a907a-30a0-47be-9620-5b476a674845.png)

## Press arrow to previous week

![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-26 at 15 07 10](https://user-images.githubusercontent.com/144948/209556969-a1f45b92-8d69-403e-a02f-07adf4a6bb0e.png)

## Click selected on Sunday

![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-26 at 15 07 35](https://user-images.githubusercontent.com/144948/209557001-987755d7-9b72-4d36-aa96-8ce9f668907f.png)

This delivers the correct events of that day (in this case a multi-day event). With the logs I can confirm, that the correct date was selected.

<img width="399" alt="Bildschirm­foto 2022-12-26 um 15 07 56" src="https://user-images.githubusercontent.com/144948/209557020-e4fd1d7d-d8a6-44ce-8d7c-5f44e932d70b.png">

There must be an additional condition in your case.

**Comment by rwbr** [comment]
I don't know, but maybe this is a similar problem like #36. There it had to do with a conversion of the date to local format. This caused an error, that I could not simulate with my time zone settings.
