### ISSUE TITLE
onEventSelected event is only triggered if you click directly on a text in the ListTile

### ISSUE THREAD

**Issue by m-gug** [rwbr/flutter_neat_and_clean_calendar#46]
Hello!
We just switched from flutter_clean_calendar to your fork and noticed that in contrast to clean_calendar here the onEventSelected event is only triggered if you click directly on a text in the ListTile. If you click on an empty area in the row, the event is not triggered.

![image](https://user-images.githubusercontent.com/79441396/209080907-c4c4ce6e-933c-49e0-adcc-fc3d44ebdf00.png)

As far as I could determine, the reason for this is probably the switch to the GestureDetector:
https://github.com/rwbr/flutter_neat_and_clean_calendar/blob/9ea7b8f1fcd12d348dc32b41773aa118be657984/lib/flutter_neat_and_clean_calendar.dart#L612

I was able to fix the problem by adding `behavior: HitTestBehavior.opaque,` to the GestureDetector (https://api.flutter.dev/flutter/rendering/HitTestBehavior.html), not sure if that fits. I will create a PR for that, maybe you can have look at it.

**Comment by rwbr** [comment]
Seems like a possible solution for that problem. Thank you for your contribution.

**Comment by rwbr** [comment]
Closed with #47
