### ISSUE TITLE
isJumpDateButtonEnabled = true this thing is missing

### ISSUE THREAD

**Issue by abdarker** [rwbr/flutter_neat_and_clean_calendar#58]
isJumpDateButtonEnabled = true this thing is missing when i add it inside 

Calender(
    isJumpDateButtonEnabled = true
    )

**Comment by rwbr** [comment]
Thank you for pointing to this topic. This is a problem of a not updated documentation. The option `isJumpDateButtonEnabled ` was cut in a previous release. With that release I introduced different option for controlling the type of the date picker. this can be done with the option `datePickerType`. This optional parameter can have one of the following values:

```
enum DatePickerType { hidden, year, date }
```

Please forget about the parameter `isJumpDateButtonEnabled `. Use `datePickerType` instead. I will fix the documentation in the next release.

Thank you for your contribution.

**Comment by abdarker** [comment]
thanks for reaching me. and what if i want by pressing that button it will lead me to current date. just like what google calender does completely remove " today" button from the top
