### ISSUE TITLE
onMonthChanged callback is not functioning as expected

### ISSUE THREAD

**Issue by nandanpraveen** [rwbr/flutter_neat_and_clean_calendar#61]
Hello! I have been working with NeatCleanCalendar and was creating a system to create events on certain weekdays like your average alarm app (For example, a 'Exercise' event that occurs on Mondays, Tuesdays, and Wednesdays). However, as it is not efficient to try and brute force the creation of all these events at once, I wanted to use the onMonthChanged callback to implement lazy loading so that the events are only created when the user navigates to the next month. However, I have been running into issues with this as the callback is not triggered when I use the navigation arrows or swipe to the next month. I was under the impression that this would trigger the calllback but it does not. I've tried looking online for solutions but to no avail. Is there an error on my part or is this something that is currently being fixed? Many thanks for your time and I hope I made sense! 
[NotWorkingCalendarCode.txt](https://github.com/rwbr/flutter_neat_and_clean_calendar/files/12409804/NotWorkingCalendarCode.txt)

**Comment by rwbr** [comment]
I can reproduce the problem. No fix yet. I have to look into that.
