### ISSUE TITLE
Not showing date color when event is added

### ISSUE THREAD

**Issue by MetasenseDevelopment** [rwbr/flutter_neat_and_clean_calendar#63]
I am facing issue regardng the color of the date , the date color becomes white on which ever date event is added if there is any perticular solution for this please reply here
note that only visible month events date color becomes white

**Comment by kwiliodev** [comment]
Having the same issue, dates with event in the current month are set to white.

**Comment by kwiliodev** [comment]
Found the fix. You should set  defaultDayColor: Colors.black,// or any color you choose other than white which is the default.
