### ISSUE TITLE
onMonthChanged is not being triggered

### ISSUE THREAD

**Issue by fbelluco** [rwbr/flutter_neat_and_clean_calendar#67]
## Environment
- Flutter version: 3.16.5
- Dart version: 3.2.3
- Library version: 0.3.15+35

## Description
I recently updated to version 0.3.15+35 from 0.2.3+11, which, according to the _changelog_, includes a fix for the `onMonthChanged` callback not being triggered. However, I am still experiencing this issue in my application.

## Expected Behavior
The `onMonthChanged` callback should be triggered as documented when changing to a different month.

## Actual Behavior
The `onMonthChanged` callback is not being triggered upon changing months.

## Code Snippet
```dart
Calendar(
  hideBottomBar: true,
  hideTodayIcon: true,
  startOnMonday: true,
  events: sReserva.hasData && sReserva.data != null
      ? sReserva.data
      : {},
  isExpandable: false,
  isExpanded: true,
  defaultDayColor: Colors.black,
  selectedColor: Colors.blue.shade800,
  todayColor: Colors.black,
  eventListBuilder: (BuildContext context,
      List<NeatCleanCalendarEvent> _selectesdEvents) {
    return SizedBox();
  },
  onDateSelected: (date) async {
    _bloc.inDay.add(date);
    await _bloc.findReserve(date);
    await _bloc.isReserve(date);
  },
  onMonthChanged: (date) async {
    await _bloc.findDays(date); // It won't trigger
  },
  locale:
      localizationDelegate.currentLocale.toString(),
  weekDays: [
    translate("SEMANA.SEG"),
    translate("SEMANA.TER"),
    translate("SEMANA.QUA"),
    translate("SEMANA.QUI"),
    translate("SEMANA.SEX"),
    translate("SEMANA.SAB"),
    translate("SEMANA.DOM"),
  ],
  dayOfWeekStyle: TextStyle(
      color: Colors.black,
      fontWeight: FontWeight.w800,
      fontSize: 11),
  );
```

**Comment by jnelle** [comment]
Same issue here and I'm using the same version

**Comment by FloPMT** [comment]
Same here. Methods nextMonth, nextWeek, previousMonth, previousWeek don't trigger the callbacks

`  void nextMonth() {
    setState(() {
      _selectedDate = Utils.nextMonth(_selectedDate);
      var firstDateOfNewMonth = Utils.firstDayOfMonth(_selectedDate);
      var lastDateOfNewMonth = Utils.lastDayOfMonth(_selectedDate);
      updateSelectedRange(firstDateOfNewMonth, lastDateOfNewMonth);
      selectedMonthsDays = _daysInMonth(_selectedDate);
      var monthFormat =
          DateFormat('MMMM yyyy', widget.locale).format(_selectedDate);
      displayMonth =
          '${monthFormat[0].toUpperCase()}${monthFormat.substring(1)}';
      _selectedEvents = eventsMap?[DateTime(
              _selectedDate.year, _selectedDate.month, _selectedDate.day)] ??
          [];
    });
  }`

**Comment by rwbr** [comment]
I can confirm, that `onMonthChanged` currently only triggers, when the user selects a day in the calendar view, that belongs to another month. 
Selecting a new date by using the date picker or changing the month by using the arrow buttons doesn't trigger.

**Comment by jnelle** [comment]
@rwbr this issue can be closed, it was fixed with the last release
