### ISSUE TITLE
Can choose date or year even icon is hidden

### ISSUE THREAD

**Issue by KeithBacalso** [rwbr/flutter_neat_and_clean_calendar#74]
Our design doesnt have that calendar icon at the top, so maybe a good solution is when we hide that calendar icon there is also an option to tap the Text(month and year) at the top and it will open a date or year picker.

**Comment by rwbr** [comment]
I think, the date picker should have an icon. Otherwise users won't be able to discover it. What if you could set the appropriate icon as a property of the calendar class?

**Comment by rwbr** [comment]
You can hide the icon. But I do not plan to add a text button or custom style button as an alternative at this moment.
