### ISSUE TITLE
how to change locale for datePicker?

### ISSUE THREAD

**Issue by koshpendi** [rwbr/flutter_neat_and_clean_calendar#79]
<img width="322" alt="image" src="https://github.com/user-attachments/assets/af743123-afc1-43dd-bb73-2c0cd4bb13be">

I changed locale for whole Calendar and works ok. But not datePicker. For example Sun, Jul 14 should be in Russian

**Comment by rwbr** [comment]
Version 0.4.0 no takes care of the selected locale of the device and adapts accourdingly.
