### ISSUE TITLE
Bug on month transition from a year to another

### ISSUE THREAD

**Issue by usernamekk** [rwbr/flutter_neat_and_clean_calendar#8]
If u navigate the calendar (not using the arrow) through the months by tapping on the dates of the next month, January 2022 does not show, rather November.

**Comment by usernamekk** [comment]
![Screenshot_20210425-152806](https://user-images.githubusercontent.com/28014560/115997667-e26ac100-a5db-11eb-9709-45e43deddb82.png)

**Comment by rwbr** [comment]
OK, let me take a look at it.
