### ISSUE TITLE
Feature Request: Option to hide listview

### ISSUE THREAD

**Issue by m-gug** [rwbr/flutter_neat_and_clean_calendar#82]
Can we have an option to hide the listview icon?

**Comment by rwbr** [comment]
Yeah, definitely. Will come in the next version.

**Comment by rwbr** [comment]
Fixed with [v0.4.7](https://github.com/rwbr/flutter_neat_and_clean_calendar/releases/tag/v0.4.7)

**Comment by m-gug** [comment]
Thank you, but with the current implementation there is a misalignment in the header if the DatePicker is hidden and the ListViewIcon is hidden. In that case the text in the header is shifted to the right.

Correct alignment with DatePicker visible:
![image](https://github.com/user-attachments/assets/e5cfd59a-dbec-42f1-a7be-881db101d6b6)

Incorrect Alignment with DatePicker hidden:
![image](https://github.com/user-attachments/assets/ee4cd76e-85a2-458f-8c98-49cf145baf56)

**Comment by rwbr** [comment]
Thank you for your comment. I will fix this as soon as possible.
